import 'package:flutter/material.dart';import 'package:flytor/core/app_export.dart';import 'package:flytor/widgets/app_bar/appbar_leading_image.dart';import 'package:flytor/widgets/app_bar/appbar_subtitle.dart';import 'package:flytor/widgets/app_bar/custom_app_bar.dart';import 'package:flytor/widgets/custom_elevated_button.dart';import 'package:flytor/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class OnboardingEighteenScreen extends StatelessWidget {OnboardingEighteenScreen({Key? key}) : super(key: key);

TextEditingController enterPannumbervalueController = TextEditingController();

TextEditingController enterAadhaarnumbervalueController = TextEditingController();

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Form(key: _formKey, child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 2.v), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Text("Progress", style: CustomTextStyles.bodySmall10)), SizedBox(height: 7.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 4.h), child: Text("60% to Complete", style: CustomTextStyles.titleSmall_2))), SizedBox(height: 5.v), _buildSectionOne(context), SizedBox(height: 36.v), _buildEnterPannumbervalue(context), SizedBox(height: 20.v), _buildPleaseUploadThe(context), SizedBox(height: 24.v), Divider(), SizedBox(height: 25.v), _buildEnterAadhaarnumbervalue(context), SizedBox(height: 23.v), Divider(), SizedBox(height: 5.v)]))), bottomNavigationBar: _buildNext(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 40.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowdown, margin: EdgeInsets.only(left: 16.h, top: 16.v, bottom: 16.v), onTap: () {onTapArrowLeft(context);}), title: AppbarSubtitle(text: "KYC", margin: EdgeInsets.only(left: 11.h))); } 
/// Section Widget
Widget _buildSectionOne(BuildContext context) { return Container(decoration: AppDecoration.fillGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder4), child: Row(children: [Container(width: 197.h, padding: EdgeInsets.symmetric(vertical: 4.v), decoration: AppDecoration.fillTeal.copyWith(borderRadius: BorderRadiusStyle.roundedBorder4), child: Row(mainAxisAlignment: MainAxisAlignment.spaceAround, children: [Container(height: 4.adaptSize, width: 4.adaptSize, decoration: BoxDecoration(color: theme.colorScheme.onPrimaryContainer, borderRadius: BorderRadius.circular(2.h))), Container(height: 4.adaptSize, width: 4.adaptSize, decoration: BoxDecoration(color: theme.colorScheme.onPrimaryContainer, borderRadius: BorderRadius.circular(2.h))), Container(height: 4.adaptSize, width: 4.adaptSize, decoration: BoxDecoration(color: theme.colorScheme.onPrimaryContainer, borderRadius: BorderRadius.circular(2.h)))])), Container(height: 4.adaptSize, width: 4.adaptSize, margin: EdgeInsets.only(left: 27.h, top: 4.v, bottom: 4.v), decoration: BoxDecoration(color: appTheme.teal400, borderRadius: BorderRadius.circular(2.h))), Spacer(flex: 47), Container(height: 4.adaptSize, width: 4.adaptSize, margin: EdgeInsets.symmetric(vertical: 4.v), decoration: BoxDecoration(color: appTheme.teal400, borderRadius: BorderRadius.circular(2.h))), Spacer(flex: 52)])); } 
/// Section Widget
Widget _buildEnterPannumbervalue(BuildContext context) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Pan Details", style: theme.textTheme.titleSmall), SizedBox(height: 18.v), CustomTextFormField(controller: enterPannumbervalueController, hintText: "Enter Pan number", textInputType: TextInputType.number, contentPadding: EdgeInsets.symmetric(horizontal: 12.h, vertical: 19.v))]); } 
/// Section Widget
Widget _buildPleaseUploadThe(BuildContext context) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Upload Pan Image", style: theme.textTheme.titleSmall), SizedBox(height: 7.v), Text("Please Upload the image in png or Jpg format.", style: CustomTextStyles.bodySmall10_1), SizedBox(height: 17.v), CustomImageView(imagePath: ImageConstant.imgRectangle255248x64, height: 48.v, width: 64.h, radius: BorderRadius.circular(4.h)), SizedBox(height: 15.v), Text("Image -1", style: CustomTextStyles.titleSmallMedium_2), SizedBox(height: 7.v), Row(children: [Padding(padding: EdgeInsets.only(top: 2.v), child: Text("File name.....png", style: CustomTextStyles.labelMediumBlueA200.copyWith(decoration: TextDecoration.underline))), Spacer(), CustomImageView(imagePath: ImageConstant.imgFramePrimarycontainer, height: 16.adaptSize, width: 16.adaptSize), CustomImageView(imagePath: ImageConstant.imgFrame, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(left: 16.h))]), SizedBox(height: 4.v), Divider(color: appTheme.teal400)]); } 
/// Section Widget
Widget _buildEnterAadhaarnumbervalue(BuildContext context) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Aadhaar Details", style: theme.textTheme.titleSmall), SizedBox(height: 7.v), Container(width: 294.h, margin: EdgeInsets.only(right: 48.h), child: Text("Please Upload the front and back side of Aadhaar image in png or jpg format.", maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodySmall10_1.copyWith(height: 1.80))), SizedBox(height: 13.v), CustomTextFormField(controller: enterAadhaarnumbervalueController, hintText: "Enter Aadhaar number", textInputAction: TextInputAction.done, textInputType: TextInputType.number, contentPadding: EdgeInsets.symmetric(horizontal: 12.h, vertical: 19.v)), SizedBox(height: 16.v), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 4.v, bottom: 2.v), child: Text("Upload Aadhaar Image", style: theme.textTheme.titleSmall)), CustomImageView(imagePath: ImageConstant.imgTwitter, height: 24.adaptSize, width: 24.adaptSize, onTap: () {onTapImgTwitter(context);})])]); } 
/// Section Widget
Widget _buildNext(BuildContext context) { return CustomElevatedButton(text: "Next", margin: EdgeInsets.only(left: 16.h, right: 16.h, bottom: 24.v), buttonStyle: CustomButtonStyles.none, decoration: CustomButtonStyles.gradientPrimaryToGrayTL81Decoration); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
/// Navigates to the onboardingTenScreen when the action is triggered.
onTapImgTwitter(BuildContext context) { Navigator.pushNamed(context, AppRoutes.onboardingTenScreen); } 
 }
