import 'package:flutter/material.dart';import 'package:flytor/core/app_export.dart';import 'package:flytor/widgets/app_bar/appbar_subtitle_two.dart';import 'package:flytor/widgets/app_bar/appbar_title.dart';import 'package:flytor/widgets/app_bar/custom_app_bar.dart';class OnboardingTwelve1Screen extends StatelessWidget {const OnboardingTwelve1Screen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: mediaQueryData.size.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 2.v), child: Padding(padding: EdgeInsets.only(left: 16.h, right: 20.h, bottom: 5.v), child: Column(children: [CustomImageView(imagePath: ImageConstant.imgDocumentFill2, height: 191.v, width: 154.h, alignment: Alignment.centerLeft), SizedBox(height: 6.v), Align(alignment: Alignment.centerLeft, child: Text("Your Documents are in review process!", style: CustomTextStyles.titleSmallMedium)), SizedBox(height: 15.v), _buildKyc(context, userImage: ImageConstant.imgFrameTeal400, kycText: "Profile", underReviewText: "Under Review", onTapKyc: () {onTapProfile(context);}), SizedBox(height: 16.v), _buildProfile1(context), SizedBox(height: 16.v), _buildSpecifications(context), SizedBox(height: 16.v), _buildKyc(context, userImage: ImageConstant.imgFrameTeal40020x20, kycText: "KYC", underReviewText: "Under Review"), SizedBox(height: 16.v), _buildBankDetails(context)])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(title: Padding(padding: EdgeInsets.only(left: 16.h), child: Column(children: [AppbarTitle(text: "Hello Pilot"), SizedBox(height: 7.v), AppbarSubtitleTwo(text: "Under Review", margin: EdgeInsets.only(right: 9.h))]))); } 
/// Section Widget
Widget _buildProfile1(BuildContext context) { return Container(padding: EdgeInsets.all(11.h), decoration: AppDecoration.outlineBluegray100.copyWith(borderRadius: BorderRadiusStyle.roundedBorder4), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgFrameTeal40020x20, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(bottom: 20.v)), Padding(padding: EdgeInsets.only(left: 8.h, bottom: 2.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Drone Details", style: CustomTextStyles.bodyMediumBlack90001), SizedBox(height: 6.v), Text("Under Review", style: theme.textTheme.labelMedium)])), Spacer(), CustomImageView(imagePath: ImageConstant.imgArrowdown, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(right: 4.h, bottom: 16.v))])); } 
/// Section Widget
Widget _buildSpecifications(BuildContext context) { return Container(padding: EdgeInsets.all(11.h), decoration: AppDecoration.outlineBluegray100.copyWith(borderRadius: BorderRadiusStyle.roundedBorder4), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgFrameTeal40020x20, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(bottom: 20.v)), Padding(padding: EdgeInsets.only(left: 8.h, top: 2.v, bottom: 2.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Specifications", style: CustomTextStyles.bodyMediumBlack90001), SizedBox(height: 5.v), Text("Under Review", style: theme.textTheme.labelMedium)])), Spacer(), CustomImageView(imagePath: ImageConstant.imgArrowdown, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(right: 4.h, bottom: 16.v))])); } 
/// Section Widget
Widget _buildBankDetails(BuildContext context) { return Container(padding: EdgeInsets.all(11.h), decoration: AppDecoration.outlineBluegray100.copyWith(borderRadius: BorderRadiusStyle.roundedBorder4), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgFrameTeal40020x20, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(bottom: 20.v)), Padding(padding: EdgeInsets.only(left: 8.h, bottom: 2.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Bank Details", style: CustomTextStyles.bodyMediumBlack90001), SizedBox(height: 6.v), Text("Under Review", style: theme.textTheme.labelMedium)])), Spacer(), CustomImageView(imagePath: ImageConstant.imgArrowdown, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(right: 4.h, bottom: 16.v))])); } 
/// Common widget
Widget _buildKyc(BuildContext context, {required String userImage, required String kycText, required String underReviewText, Function? onTapKyc, }) { return GestureDetector(onTap: () {onTapKyc!.call();}, child: Container(padding: EdgeInsets.all(11.h), decoration: AppDecoration.outlineBluegray100.copyWith(borderRadius: BorderRadiusStyle.roundedBorder4), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: userImage, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(bottom: 20.v)), Padding(padding: EdgeInsets.only(left: 8.h, bottom: 2.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(kycText, style: CustomTextStyles.bodyMediumBlack90001.copyWith(color: appTheme.black90001)), SizedBox(height: 6.v), Text(underReviewText, style: theme.textTheme.labelMedium!.copyWith(color: appTheme.orangeA200))])), Spacer(), CustomImageView(imagePath: ImageConstant.imgArrowdown, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(right: 4.h, bottom: 16.v))]))); } 
/// Navigates to the onboardingNineScreen when the action is triggered.
onTapProfile(BuildContext context) { Navigator.pushNamed(context, AppRoutes.onboardingNineScreen); } 
 }
